blank_issues_enabled: false
contact_links:
  - name: DNN Community Forums
    url: https://dnncommunity.org/forums
    about: Get help, solicit feedback and discuss new ideas regarding DNN Platform.
  - name: DNN Documentation
    url: https://docs.dnncommunity.org
    about: Learn more about DNN Platform.
