name: Open Merged PR to release/9.11.0 Branch

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  open-merged-pr-to-release-branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - uses: actions/checkout@v3

      - uses: peterjgrainger/action-create-branch@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: v9.11.0/${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: v9.11.0/${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}
          destination_branch: release/9.11.0
          pr_title: v9.11.0 ${{ github.event.pull_request.title }}
          pr_body: |
            Applying #${{ github.event.pull_request.number }} to release/9.11.0
            ${{ github.event.pull_request.body }}
          pr_label: ${{ join(github.event.pull_request.labels.*.name) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
