name: Update Versions
on: create

# Sets the manifest and other files version upon creation of a release branch
jobs:
  updateVersions:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch' && startsWith(github.event.ref, 'release/') }}
    steps:
      - uses: actions/checkout@v4

      - name: Get the release branch version
        uses: valadas/get-release-branch-version@v1.1.0
        id: branchVersion

      - name: Set versions
        uses: valadas/set-dnn-manifest-versions@v1.3.0
        with:
          version: ${{ steps.branchVersion.outputs.manifestSafeVersionString }}
          skipFile: "./Build/Tasks/unversionedManifests.txt"
          includeSolutionInfo: true
          includeIssueTemplates: true
          includePackageJson: true
          includeDnnReactCommon: true

      - name: Update Yarn versions
        shell: pwsh
        run: yarn install --mode=update-lockfile --no-immutable

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Updates versions as per release candidate creation
          title: Updates versions as per release candidate creation
          body: This is a release management task and we are self-approving it for that reason.
          # A comma separated list of labels.
          labels: "Type: Build/Release"
          # The pull request branch name.
          branch: update-versions/patch
          # The branch suffix type.
          branch-suffix: short-commit-hash
